<?php
/**
 * Login and registration form.
 *
 * This override keeps WooCommerce hooks, nonces and account settings intact while
 * presenting both actions as the primary content of the Samirarte account page.
 *
 * @package Samirarte_Boutique
 * @version 9.9.0
 */

defined( 'ABSPATH' ) || exit;

ob_start();
do_action( 'woocommerce_before_customer_login_form' );
$before_login_markup = ob_get_clean();

echo $before_login_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output from registered WooCommerce hooks.

$registration_enabled     = 'yes' === get_option( 'woocommerce_enable_myaccount_registration' );
$nextend_already_rendered  = (bool) preg_match( '/nsl-container|nextend-social-login|data-plugin=["\']nsl/i', $before_login_markup );
$google_login_markup      = samirarte_boutique_google_login_markup( $nextend_already_rendered, esc_html__( 'Continuar con Google', 'samirarte-boutique' ) );
$google_register_markup   = samirarte_boutique_google_login_markup( $nextend_already_rendered, esc_html__( 'Registrarse con Google', 'samirarte-boutique' ) );
?>

<?php samirarte_boutique_account_opening_gift_notice(); ?>

<section class="sam-account-access" aria-label="<?php echo esc_attr__( 'Acceso y registro de cliente', 'samirarte-boutique' ); ?>">
	<div class="sam-account-forms<?php echo $registration_enabled ? '' : ' sam-account-forms--login-only'; ?>" id="customer_login">
		<section class="sam-account-card sam-account-card--login" aria-labelledby="sam-account-login-title">
			<p class="sam-account-card__eyebrow"><?php echo esc_html__( 'Ya soy cliente', 'samirarte-boutique' ); ?></p>
			<h2 id="sam-account-login-title"><?php echo esc_html__( 'Acceder', 'samirarte-boutique' ); ?></h2>
			<p class="sam-account-card__intro"><?php echo esc_html__( 'Entra para consultar tus pedidos, datos y preferencias.', 'samirarte-boutique' ); ?></p>

			<?php if ( $google_login_markup ) : ?>
				<div class="sam-account-card__social" data-sam-nextend-login="access">
					<?php echo $google_login_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Markup generated by Nextend. ?>
				</div>
				<p class="sam-account-card__divider"><span><?php echo esc_html__( 'o con tu correo', 'samirarte-boutique' ); ?></span></p>
			<?php endif; ?>

			<form class="woocommerce-form woocommerce-form-login login" method="post" novalidate>
				<?php do_action( 'woocommerce_login_form_start' ); ?>

				<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
					<label for="username"><?php echo esc_html__( 'Correo electrónico o nombre de usuario', 'samirarte-boutique' ); ?>&nbsp;<span class="required" aria-hidden="true">*</span><span class="screen-reader-text"><?php esc_html_e( 'Required', 'woocommerce' ); ?></span></label>
					<input type="text" class="woocommerce-Input woocommerce-Input--text input-text" name="username" id="username" autocomplete="username" value="<?php echo ( ! empty( $_POST['username'] ) && is_string( $_POST['username'] ) ) ? esc_attr( wp_unslash( $_POST['username'] ) ) : ''; ?>" required aria-required="true">
				</p>
				<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
					<label for="password"><?php echo esc_html__( 'Contraseña', 'samirarte-boutique' ); ?>&nbsp;<span class="required" aria-hidden="true">*</span><span class="screen-reader-text"><?php esc_html_e( 'Required', 'woocommerce' ); ?></span></label>
					<input class="woocommerce-Input woocommerce-Input--text input-text" type="password" name="password" id="password" autocomplete="current-password" required aria-required="true">
				</p>

				<?php do_action( 'woocommerce_login_form' ); ?>

				<div class="sam-account-login-meta">
					<label class="woocommerce-form__label woocommerce-form__label-for-checkbox woocommerce-form-login__rememberme">
						<input class="woocommerce-form__input woocommerce-form__input-checkbox" name="rememberme" type="checkbox" id="rememberme" value="forever">
						<span><?php echo esc_html__( 'Mantener la sesión iniciada', 'samirarte-boutique' ); ?></span>
					</label>
					<a class="sam-account-lost-password" href="<?php echo esc_url( wp_lostpassword_url() ); ?>"><?php echo esc_html__( 'He olvidado mi contraseña', 'samirarte-boutique' ); ?></a>
				</div>
				<p class="form-row sam-account-card__actions">
					<?php wp_nonce_field( 'woocommerce-login', 'woocommerce-login-nonce' ); ?>
					<button type="submit" class="woocommerce-button button woocommerce-form-login__submit<?php $sam_btn_class = function_exists( 'wc_wp_theme_get_element_class_name' ) ? wc_wp_theme_get_element_class_name( 'button' ) : ''; echo $sam_btn_class ? ' ' . esc_attr( $sam_btn_class ) : ''; ?>" name="login" value="<?php echo esc_attr__( 'Acceder', 'samirarte-boutique' ); ?>"><?php echo esc_html__( 'Acceder', 'samirarte-boutique' ); ?></button>
				</p>

				<?php do_action( 'woocommerce_login_form_end' ); ?>
			</form>
		</section>

		<?php if ( $registration_enabled ) : ?>
			<section class="sam-account-card sam-account-card--register" id="registro" tabindex="-1" aria-labelledby="sam-account-register-title">
				<p class="sam-account-card__badge"><?php echo esc_html__( 'Preapertura', 'samirarte-boutique' ); ?></p>
				<h2 id="sam-account-register-title"><?php echo esc_html__( 'Crear cuenta', 'samirarte-boutique' ); ?></h2>
				<p class="sam-account-card__intro"><?php echo esc_html__( 'Regístrate para guardar tus datos y recibir el regalo exclusivo de apertura con tu primer pedido.', 'samirarte-boutique' ); ?></p>

				<?php if ( $google_register_markup ) : ?>
					<div class="sam-account-card__social" data-sam-nextend-login="register">
						<?php echo $google_register_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Markup generated by Nextend. ?>
					</div>
					<p class="sam-account-card__divider"><span><?php echo esc_html__( 'o con tu correo', 'samirarte-boutique' ); ?></span></p>
				<?php endif; ?>

				<form method="post" class="woocommerce-form woocommerce-form-register register" <?php do_action( 'woocommerce_register_form_tag' ); ?>>
					<?php do_action( 'woocommerce_register_form_start' ); ?>

					<?php if ( 'no' === get_option( 'woocommerce_registration_generate_username' ) ) : ?>
						<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
							<label for="reg_username"><?php esc_html_e( 'Username', 'woocommerce' ); ?>&nbsp;<span class="required" aria-hidden="true">*</span><span class="screen-reader-text"><?php esc_html_e( 'Required', 'woocommerce' ); ?></span></label>
							<input type="text" class="woocommerce-Input woocommerce-Input--text input-text" name="username" id="reg_username" autocomplete="username" value="<?php echo ( ! empty( $_POST['username'] ) && is_string( $_POST['username'] ) ) ? esc_attr( wp_unslash( $_POST['username'] ) ) : ''; ?>" required aria-required="true">
						</p>
					<?php endif; ?>

					<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
						<label for="reg_email"><?php echo esc_html__( 'Correo electrónico', 'samirarte-boutique' ); ?>&nbsp;<span class="required" aria-hidden="true">*</span><span class="screen-reader-text"><?php esc_html_e( 'Required', 'woocommerce' ); ?></span></label>
						<input type="email" class="woocommerce-Input woocommerce-Input--text input-text" name="email" id="reg_email" autocomplete="email" value="<?php echo ( ! empty( $_POST['email'] ) && is_string( $_POST['email'] ) ) ? esc_attr( wp_unslash( $_POST['email'] ) ) : ''; ?>" required aria-required="true">
					</p>

					<?php if ( 'no' === get_option( 'woocommerce_registration_generate_password' ) ) : ?>
						<p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
							<label for="reg_password"><?php esc_html_e( 'Password', 'woocommerce' ); ?>&nbsp;<span class="required" aria-hidden="true">*</span><span class="screen-reader-text"><?php esc_html_e( 'Required', 'woocommerce' ); ?></span></label>
							<input type="password" class="woocommerce-Input woocommerce-Input--text input-text" name="password" id="reg_password" autocomplete="new-password" required aria-required="true">
						</p>
					<?php else : ?>
						<p class="sam-account-password-note"><?php echo esc_html__( 'Te enviaremos un enlace seguro para crear tu contraseña.', 'samirarte-boutique' ); ?></p>
					<?php endif; ?>

					<?php do_action( 'woocommerce_register_form' ); ?>

					<p class="woocommerce-form-row form-row">
						<?php wp_nonce_field( 'woocommerce-register', 'woocommerce-register-nonce' ); ?>
						<button type="submit" class="woocommerce-Button woocommerce-button button<?php $sam_btn_class = function_exists( 'wc_wp_theme_get_element_class_name' ) ? wc_wp_theme_get_element_class_name( 'button' ) : ''; echo $sam_btn_class ? ' ' . esc_attr( $sam_btn_class ) : ''; ?> woocommerce-form-register__submit" name="register" value="<?php esc_attr_e( 'Register', 'woocommerce' ); ?>"><?php echo esc_html__( 'Crear cuenta', 'samirarte-boutique' ); ?></button>
					</p>

					<?php do_action( 'woocommerce_register_form_end' ); ?>
				</form>
			</section>
		<?php endif; ?>
	</div>
</section>

<?php do_action( 'woocommerce_after_customer_login_form' ); ?>
